[package]
name = "pls-bitcoin-lib"
version = "0.2.1"
edition = "2021"
description = "A Bitcoin contracts constructor lib for Private Law Society project"
license = "MIT"

[dependencies]
bitcoin = "0.32.102"

[dev-dependencies]
bitcoin = { version = "0.32.102", features = ["encoding", "rand"] }
rstest = "0.27.0"
nigiri-rs = { version = "0.6", features = ["fixtures"] }
tokio = { version = "1.53.1", features = ["macros", "rt", "rt-multi-thread"] }
